version = 0.1
[default.deploy.parameters]
stack_name = "website-status-checker"
resolve_s3 = true
s3_prefix = "website-status-checker"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
